flush-interval = 10

[sources]
  [sources.statsd.hamish]
  host = "0.0.0.0"
  port = 8125
  forwards = ["filters.delay.ten"]

[filters]
[filters.delay.ten]
  tolerance = 10
  forwards = ["sinks.console"]

[sinks]
  [sinks.console]
